server {
    listen 80;
    index index.php index.html;
    root /var/www/html;

    # Support for SEO friendly URLs
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Pass PHP scripts to PHP-FPM container via FastCGI
    location ~ \.php$ {
        fastcgi_pass app:9000; # 'app' matches the service name in docker-compose.yml
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
